"""added posts

Revision ID: 1bf088a90127
Revises: 37141e3a96ba
Create Date: 2024-10-15 10:35:00.511354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bf088a90127'
down_revision = '37141e3a96ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('address', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'users', ['address'])
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=120), server_default=sa.text("('')"), nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'address')
    op.drop_table('posts')
    # ### end Alembic commands ###
